# Generated by Django 5.2.15 on 2026-06-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
